version: '3'
services:
  therm-doc:
    build:
      context: .
      args:
        - PYTHON_PACKAGES=pandas==1.5.0 psycopg2==2.9.5 PyMySQL==1.0.2 requests==2.27.1 selenium==4.7.2 SQLAlchemy==1.4.44 webdriver_manager==3.8.4 wget==3.2
      platform:
        - os: darwin
          arch: arm64
          variant: v8
    command: python ./thermo.py
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - PYTHON-PATH=/app
    working_dir: /app
